### ISSUE TITLE
Pragzip Error got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by agoertz-fls** [mxmlnkn/pragzip#15]
Hi,

I recently noticed an error like this when using pragzip:

```
[Info] Reopening the gzip with the pragzip backend...
[Info] Checking for (compressed) TAR file raised an exception: __init__() got an unexpected keyword argument 'verbose'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ratarmountcore/factory.py", line 58, in openMountSource
    return SQLiteIndexedTar(fileOrPath, **options)
  File "/usr/lib/python3.10/site-packages/ratarmountcore/SQLiteIndexedTar.py", line 728, in __init__
    self._loadOrStoreCompressionOffsets()  # load
  File "/usr/lib/python3.10/site-packages/ratarmountcore/SQLiteIndexedTar.py", line 1520, in _loadOrStoreCompressionOffsets
    self._reloadWithPragzip()
  File "/usr/lib/python3.10/site-packages/ratarmountcore/SQLiteIndexedTar.py", line 1575, in _reloadWithPragzip
    self.tarFileObject = pragzip.PragzipFile(
  File "pragzip.pyx", line 196, in pragzip.PragzipFile.__init__
TypeError: __init__() got an unexpected keyword argument 'verbose'
```

In the githubrepo it looks like the verbose parameter is not there.
[self.rawFileObject, parallelization=self.parallelization, verbose=self.printDebug >= 2](https://github.com/mxmlnkn/ratarmount/blob/a47eadd06ca817ad4afb1c42a4dec52381732229/core/ratarmountcore/SQLiteIndexedTar.py#L1576)

Kind regards,
Alex

**Comment by agoertz-fls** [comment]
Sorry wrong project
